language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support
jdk:
  - oraclejdk8

sudo: required


